version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"   # Elasticsearch API
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"   # Kibana UI
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_service
      - ELASTICSEARCH_PASSWORD=MyKibana@2025
      - I18N_LOCALE=zh-CN 

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"   # Beats input
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    environment:
      - xpack.monitoring.enabled=false
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      
volumes:
  es-data:
